# Generated by Django 5.0.7 on 2025-03-25 06:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='github_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='github auth'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='google auth'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='telegram auth'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile_picture.png', null=True, upload_to='profile_pictures/'),
        ),
        migrations.CreateModel(
            name='AdditionalUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Describe yourself')),
                ('specialty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Specialty')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], default='N', max_length=1, verbose_name='Gender')),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='Age')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Region')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('google_link', models.URLField(blank=True, null=True, verbose_name='Google link')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram link')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='GitHub link')),
                ('head_hunter_link', models.URLField(blank=True, null=True, verbose_name='HeadHunter link')),
                ('habr_link', models.URLField(blank=True, null=True, verbose_name='Habr link')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='language')),
                ('theme', models.CharField(default='dark', max_length=10, verbose_name='theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
